cc_library (
    name = "part01",
    hdrs = ["part01.h"],
)

cc_library (
    name = "part02",
    hdrs = ["part02.h"],
)

cc_binary (
    name = "main",
    srcs = ["main.cc"],
    deps = [
        ":part01",
        ":part02"
    ]
)
